SELECT TEHF.TAX_ID, TEHF.TAX_NAME, hfsc.HISTORY_FACT_STATUS_DESC AS TAX_ENTITY_STATUS, TEHF.SSN,dd.DATE_VALUE AS TAX_ENTITY_EFF_DATE, dd2.DATE_VALUE AS TAX_ENTITY_Term_DATE  
FROM  
   	PAYOR_DW.TAX_ENTITY TEHF 
LEFT JOIN 
   	payor_dw.HISTORY_FACT_STATUS_CODE hfsc ON TEHF.TAX_ENTITY_STATUS = hfsc.HISTORY_FACT_STATUS_CODE 
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON TEHF.TAX_ENTITY_EFF_DATE_KEY = dd.DATE_KEY
LEFT JOIN
    payor_dw.DATE_DIMENSION dd2 ON TEHF.TAX_ENTITY_TERM_DATE_KEY = dd2.DATE_KEY