 SELECT 
    pf.PAYMENT_NUMBER AS CHECK_NUMBER,
    dd.DATE_VALUE AS PAYMENT_DATE,
    ptc.PAYMENT_TYPE_DESC AS Payment_Type,
    pf.PAYMENT_AMOUNT AS Amount,
    ptc2.PAYABLE_TYPE_DESC AS Payable_Type,
    psc.PAYMENT_STATUS_NAME ,
    s.SUPPLIER_HCC_ID AS Payee_ID,
    pf.PAY_TO_NAME AS Payee_Name,
    TEHF.TAX_ID, 
    TEHF.TAX_NAME, 
    hfsc.HISTORY_FACT_STATUS_DESC AS TAX_ENTITY_STATUS, 
    TEHF.SSN,
    dd1.DATE_VALUE AS TAX_ENTITY_EFF_DATE, 
    dd2.DATE_VALUE AS TAX_ENTITY_Term_DATE,
    pa.ADDRESS_LINE AS Pay_To_Address,
    pf.PAYMENT_CYCLE_KEY AS Payment_Cycle_ID,
    pf.PAYMENT_FACT_KEY AS Transaction_Num,
    pf.PAYMENT_BATCH_KEY AS Payment_Batch_ID
FROM 
    PAYMENT_FACT pf
LEFT JOIN 
    PAYMENT_TYPE_CODE ptc ON pf.PAYMENT_TYPE_KEY = ptc.PAYMENT_TYPE_KEY
LEFT JOIN 
    DATE_DIMENSION dd ON pf.PAYMENT_DATE_KEY = dd.DATE_KEY
LEFT JOIN 
    PAYABLE_TYPE_CODE ptc2 ON pf.PAYABLE_TYPE_CODE = ptc2.PAYABLE_TYPE_CODE
LEFT JOIN 
    PAYMENT_STATUS_CODE psc ON pf.PAYMENT_STATUS_CODE = psc.PAYMENT_STATUS_CODE
LEFT JOIN 
    POSTAL_ADDRESS pa ON pf.PAYMENT_ADDRESS_KEY = pa.POSTAL_ADDRESS_KEY
LEFT JOIN 
    supplier s ON pf.SUPPLIER_KEY = s.SUPPLIER_KEY 
LEFT JOIN 
    PAYOR_DW.TAX_ENTITY TEHF ON S.TAX_ENTITY_KEY = TEHF.TAX_ENTITY_KEY 
LEFT JOIN
    payor_dw.DATE_DIMENSION dd1 ON TEHF.TAX_ENTITY_EFF_DATE_KEY = dd.DATE_KEY
LEFT JOIN
    payor_dw.DATE_DIMENSION dd2 ON TEHF.TAX_ENTITY_TERM_DATE_KEY = dd2.DATE_KEY
LEFT JOIN 
    payor_dw.HISTORY_FACT_STATUS_CODE hfsc ON TEHF.TAX_ENTITY_STATUS = hfsc.HISTORY_FACT_STATUS_CODE 
WHERE 
    --pf.PAYMENT_AMOUNT > 0 
    pf.PAYMENT_AMOUNT != 0 
    --AND pf.PAYMENT_NUMBER = '7966'
--     AND TRUNC(dd.DATE_VALUE) = TO_DATE('2024-09-05', 'YYYY-MM-DD')
    --AND dd.DATE_VALUE >= TO_TIMESTAMP('2024-07-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND dd.DATE_VALUE < TO_TIMESTAMP('2024-07-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
ORDER BY 
    pf.PAYMENT_NUMBER;