WITH RankedClaims AS (
    SELECT cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC ) AS rn
    FROM CLAIM_FACT cf 
    WHERE 
        cf.IS_CONVERTED = 'N' 
        AND cf.IS_TRIAL_CLAIM = 'N'
        AND cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
SELECT 
    rc.CLAIM_HCC_ID,rc.CLAIM_STATUS,aclf.CLAIM_LINE_HCC_ID,aclf.SERVICE_CODE,clftm.MODIFIER_CODE ,
    s.SERVICE_LONG_DESC AS SERVICE_DESC,m.MODIFIER_NAME, 
    rc.MOST_RECENT_PROCESS_TIME,rc.ENTRY_TIME   
FROM RankedClaims rc
LEFT JOIN ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY 
LEFT JOIN SERVICE s ON aclf.SERVICE_CODE = s.SERVICE_CODE 
LEFT JOIN CLAIM_LINE_FACT_TO_MODIFIER clftm ON aclf.CLAIM_LINE_FACT_KEY = clftm.CLAIM_LINE_FACT_KEY 
LEFT JOIN MODIFIER m ON clftm.MODIFIER_CODE = m.MODIFIER_CODE 
WHERE 
rn = 1
AND rc.CLAIM_HCC_ID = 2024183004613

-------------------------------------------------------------------------------------------------------------------------------------
 WITH RankedClaims AS (
    SELECT cf.*,ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) AS rn
    FROM CLAIM_FACT cf 
    WHERE 
        cf.IS_CONVERTED = 'N' 
        AND cf.IS_TRIAL_CLAIM = 'N'
        AND cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
        )       
SELECT rc.CLAIM_HCC_ID,rc.CLAIM_STATUS,aclf.CLAIM_LINE_HCC_ID,aclf.SERVICE_CODE,
    LISTAGG(DISTINCT clftm.MODIFIER_CODE, ', ') WITHIN GROUP (ORDER BY clftm.MODIFIER_CODE) AS MODIFIER_CODES,
    s.SERVICE_LONG_DESC AS SERVICE_DESC,rc.MOST_RECENT_PROCESS_TIME,rc.ENTRY_TIME   
    FROM RankedClaims rc
    LEFT JOIN ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY 
    LEFT JOIN SERVICE s ON aclf.SERVICE_CODE = s.SERVICE_CODE 
    LEFT JOIN CLAIM_LINE_FACT_TO_MODIFIER clftm ON aclf.CLAIM_LINE_FACT_KEY = clftm.CLAIM_LINE_FACT_KEY 
    WHERE rn = 1 
    --AND rc.CLAIM_HCC_ID = 2024183004613
    --AND rc.CLAIM_HCC_ID = '2024194007199'
    AND aclf.SERVICE_CODE = 'T2033' AND clftm.MODIFIER_CODE IN ('U6', '99')
    GROUP BY 
        rc.CLAIM_HCC_ID,rc.CLAIM_STATUS,aclf.CLAIM_LINE_HCC_ID,aclf.SERVICE_CODE,s.SERVICE_LONG_DESC,rc.MOST_RECENT_PROCESS_TIME,rc.ENTRY_TIME
    HAVING COUNT(DISTINCT clftm.MODIFIER_CODE) = 2
    ORDER BY 
        rc.CLAIM_HCC_ID,aclf.CLAIM_LINE_HCC_ID;