   
WITH RecentClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) as row_num
    FROM
        payor_dw.claim_fact cf
    WHERE
        cf.IS_CONVERTED = 'N' AND
        cf.IS_TRIAL_CLAIM = 'N' AND 
        cf.IS_CURRENT = 'Y' 
--        cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
SELECT DISTINCT  
    rc.CLAIM_HCC_ID,
	aclf.CLAIM_LINE_HCC_ID,
    rc.CLAIM_STATUS,
    rc.CLAIM_TYPE_NAME,
    csc.CLAIM_SOURCE_NAME,
    rc.SUBMITTED_SUBSCRIBER_ID,
    aclf.SERVICE_CODE,
    aclf.SERVICE_DESC,
    ncif.NDC_CODE ,
    rc.SI_SUPPLIER_NPI,
    ashf.SUPPLIER_NPI  AS ASHF_SUPPLIER_NPI,
    RC.SI_SUPPLIER_ID,
    ashf.SUPPLIER_HCC_ID AS ASHF_SUPPLIER_HCC_ID,
    rc.SI_SUPPLIER_NAME,
    ashf.SUPPLIER_NAME AS ASHF_SUPPLIER_NAME,
    dd.DATE_VALUE AS RECEIPT_DATE,
    rc.ENTRY_TIME,
    rc.MOST_RECENT_PROCESS_TIME
FROM
    RecentClaims rc
LEFT JOIN
    payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
LEFT JOIN
    payor_dw.ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY 
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN
    payor_dw.SUPPLIER ashf ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
LEFT JOIN
    payor_dw.CLAIM_LN_FACT_TO_NDC_CODE_INFO clftnci ON aclf.CLAIM_LINE_FACT_KEY = clftnci.CLAIM_LINE_FACT_KEY 
LEFT JOIN
    payor_dw.NDC_CODE_INFO_FACT ncif ON clftnci.NDC_CODE_INFO_KEY = ncif.NDC_CODE_INFO_KEY 
WHERE
    rc.row_num = 1
--    AND ncif.NDC_CODE IS NOT NULL 
--    AND aclf.SERVICE_DESC IS NOT NULL 
--    AND aclf.SERVICE_DESC LIKE 'UP%'
--    AND rc.CLAIM_HCC_ID = '2024272003758'
	AND aclf.SERVICE_DESC IS NOT NULL 
  	AND INSTR(aclf.SERVICE_DESC, ncif.NDC_CODE) > 0;s