
SELECT * 
FROM AUDIT_LOG_ENTRY_FACT alef 
LEFT JOIN
    payor_dw.ACTION_TYPE_CODE atc ON alef.ACTION_TYPE_CODE = atc.ACTION_TYPE_CODE
LEFT JOIN
	payor_dw.USER_ACCOUNT ua ON alef.HCC_USER_ID = ua.USER_ACCOUNT_KEY
WHERE ALEF.AUDIT_LOG_KEY  = '12683603'