SELECT   
     m.MEMBER_HCC_ID,
	 m.MEMBER_FULL_NAME,
	 m.MEMBER_STATUS ,
     m.MEMBER_GENDER_CODE,
     D1.DATE_VALUE AS MEMBER_EFFECTIVE_DATE,
     D2.DATE_VALUE AS MEMBER_RECEIPT_DATE,
	 effDt.DATE_VALUE AS Version_eff_date,
     expDt.DATE_VALUE AS Version_exp_date
 FROM 
    PAYOR_DW.MEMBER m
    LEFT JOIN payor_dw.DATE_DIMENSION D1 ON m.MEMBER_EFFECTIVE_DATE_KEY = D1.DATE_KEY 
    LEFT JOIN payor_dw.DATE_DIMENSION D2 ON m.MEMBER_RECEIPT_DATE_KEY = D2.DATE_KEY
    LEFT JOIN payor_dw.DATE_DIMENSION effDt ON m.VERSION_EFF_DATE_KEY = effDt.DATE_KEY 
    LEFT JOIN payor_dw.DATE_DIMENSION expDt ON m.VERSION_EXP_DATE_KEY = expDt.DATE_KEY
WHERE 
     m.MEMBER_STATUS = 'a'
     AND D2.DATE_VALUE < TO_TIMESTAMP('2024-11-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')