 SELECT 
-- 	 m.MEMBER_HISTORY_FACT_KEY ,
-- 	 m.MEMBER_KEY ,
 	 m.MEMBER_HCC_ID,
	 m.MEMBER_FULL_NAME,
	 m.MEMBER_STATUS ,
     m.MEMBER_GENDER_CODE,
	 mhftsl.ROLE_NAME ,
	 sl.SUPPLIER_LOCATION_NAME,
--	 sl.SUPPLIER_LOCATION_KEY,
	 sl.SUPPLIER_LOCATION_HCC_ID,
	-- m.ENDOR_EXP_DATE,
	 D1.DATE_VALUE AS Version_eff_date,
     D2.DATE_VALUE AS Version_exp_date
--	 prhf.PRACTITIONER_ROLE_NAME
 FROM 
    PAYOR_DW.MEMBER m
--	PAYOR_DW.ALL_MEMBER_VERSION_HIST_FACT m
 LEFT JOIN PAYOR_DW.MEMBER_HIST_FACT_TO_SUPPL_LOC mhftsl ON m.MEMBER_HISTORY_FACT_KEY = mhftsl.MEMBER_HISTORY_FACT_KEY 
 LEFT JOIN PAYOR_DW.SUPPLIER_LOCATION sl ON mhftsl.SUPPLIER_LOCATION_KEY = sl.SUPPLIER_LOCATION_KEY 
 LEFT JOIN PAYOR_DW.DATE_DIMENSION D1 ON m.VERSION_EFF_DATE_KEY = D1.DATE_KEY
 LEFT JOIN PAYOR_DW.DATE_DIMENSION D2 ON m.VERSION_EXP_DATE_KEY = D2.DATE_KEY
 --LEFT JOIN PAYOR_DW.PRACTITIONER_ROLE_HISTORY_FACT prhf ON sl.SUPPLIER_LOCATION_KEY = prhf.SUPPLIER_LOCATION_KEY 
-- LEFT JOIN payor_dw.DATE_DIMENSION effDt ON prhf.VERSION_EFF_DATE_KEY = effDt.DATE_KEY 
-- LEFT JOIN payor_dw.DATE_DIMENSION expDt ON prhf.VERSION_EXP_DATE_KEY = expDt.DATE_KEY
 WHERE 
--  (D1.DATE_VALUE <= SYSDATE) AND (D2.DATE_VALUE > SYSDATE) AND 
--  ((m.ENDOR_EXP_DATE > SYSDATE )OR (m.ENDOR_EXP_DATE is NULL)) AND 
  --m.MEMBER_HCC_ID = '91197524F' 
   mhftsl.ROLE_NAME IS NOT NULL
  --m.MEMBER_HCC_ID = '90102411A'
   AND sl.SUPPLIER_LOCATION_HCC_ID IN ('1000212', '31658', '1000220')

---------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------

 ----------- Member - PCP - SUPPLIER LOC - TAX ID -------------------
 
 
    
  SELECT 
-- 	 m.MEMBER_HISTORY_FACT_KEY ,
-- 	 m.MEMBER_KEY ,
 	 m.MEMBER_HCC_ID,
	 m.MEMBER_FULL_NAME,
	 m.MEMBER_STATUS ,
     m.MEMBER_GENDER_CODE,
	 mhftsl.ROLE_NAME ,
	 sl.SUPPLIER_LOCATION_NAME,
--	 sl.SUPPLIER_LOCATION_KEY,
	 sl.SUPPLIER_LOCATION_HCC_ID,
	 s.TAX_ID ,
	 s.TAX_NAME ,
	 s.SUPPLIER_HCC_ID ,
	 s.SUPPLIER_NAME ,
	-- m.ENDOR_EXP_DATE,
	 D1.DATE_VALUE AS Version_eff_date,
     D2.DATE_VALUE AS Version_exp_date
--	 prhf.PRACTITIONER_ROLE_NAME
 FROM 
    PAYOR_DW."MEMBER" m
--	PAYOR_DW.ALL_MEMBER_VERSION_HIST_FACT m
 LEFT JOIN PAYOR_DW.MEMBER_HIST_FACT_TO_SUPPL_LOC mhftsl ON m.MEMBER_HISTORY_FACT_KEY = mhftsl.MEMBER_HISTORY_FACT_KEY 
 LEFT JOIN PAYOR_DW.SUPPLIER_LOCATION sl ON mhftsl.SUPPLIER_LOCATION_KEY = sl.SUPPLIER_LOCATION_KEY 
 LEFT JOIN PAYOR_DW.DATE_DIMENSION D1 ON m.VERSION_EFF_DATE_KEY = D1.DATE_KEY
 LEFT JOIN PAYOR_DW.DATE_DIMENSION D2 ON m.VERSION_EXP_DATE_KEY = D2.DATE_KEY
 LEFT JOIN payor_dw.SUPPLIER s ON sl.SUPPLIER_KEY = s.SUPPLIER_KEY 
 --LEFT JOIN PAYOR_DW.PRACTITIONER_ROLE_HISTORY_FACT prhf ON sl.SUPPLIER_LOCATION_KEY = prhf.SUPPLIER_LOCATION_KEY 
-- LEFT JOIN payor_dw.DATE_DIMENSION effDt ON prhf.VERSION_EFF_DATE_KEY = effDt.DATE_KEY 
-- LEFT JOIN payor_dw.DATE_DIMENSION expDt ON prhf.VERSION_EXP_DATE_KEY = expDt.DATE_KEY
 WHERE 
--  (D1.DATE_VALUE <= SYSDATE) AND (D2.DATE_VALUE > SYSDATE) AND 
--  ((m.ENDOR_EXP_DATE > SYSDATE )OR (m.ENDOR_EXP_DATE is NULL)) AND 
  --m.MEMBER_HCC_ID = '91197524F' 
   mhftsl.ROLE_NAME IS NOT NULL
  --m.MEMBER_HCC_ID = '90102411A'
   --AND sl.SUPPLIER_LOCATION_HCC_ID IN ('1000212', '31658', '1000220')
   AND s.TAX_ID IN ('95-2977147')


   
