  WITH RankedClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) AS rn
    FROM
        CLAIM_FACT cf
   WHERE
       cf.IS_CONVERTED = 'N'
       AND cf.IS_TRIAL_CLAIM = 'N'
       AND cf.IS_CURRENT = 'Y'   
	   AND cf.MOST_RECENT_PROCESS_TIME >= TO_TIMESTAMP('2024-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
	   AND cf.MOST_RECENT_PROCESS_TIME < TO_TIMESTAMP('2024-11-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')    
)
SELECT
    rc.CLAIM_HCC_ID,
    rc.CLAIM_STATUS,
    rc.SUBMITTED_SUBSCRIBER_ID,
    dd.DATE_VALUE AS Receipt_Date,
    rc.ENTRY_TIME,
    rc.MOST_RECENT_PROCESS_TIME,
--    al.ACTION_TYPE_CODE ,
    atc.ACTION_TYPE_DESC ,
    al.ENTRY_TIME  AS LOG_TIME,
    al.LOG_NOTE,
    al.MESSAGE_DESC, 
    ua.USER_NAME ,
    al.HCC_USER_ID 
FROM RankedClaims rc
LEFT JOIN payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN payor_dw.supplier ashf ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
LEFT JOIN PAYOR_DW.TAX_ENTITY TE ON ashf.TAX_ENTITY_KEY = TE.TAX_ENTITY_KEY 
LEFT JOIN payor_dw.AUDIT_LOG_ENTRY_FACT al ON rc.AUDIT_LOG_KEY = al.AUDIT_LOG_KEY
LEFT JOIN payor_dw.ACTION_TYPE_CODE atc ON al.ACTION_TYPE_CODE = atc.ACTION_TYPE_CODE
LEFT JOIN payor_dw.USER_ACCOUNT ua ON al.HCC_USER_ID = ua.USER_ACCOUNT_KEY
WHERE rn = 1  AND al.ACTION_TYPE_CODE = 11
--AND CLAIM_HCC_ID = '2024157000279'