   
WITH RecentClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) as row_num
    FROM
        payor_dw.claim_fact cf
    WHERE
        cf.IS_CONVERTED = 'N' AND
        cf.IS_TRIAL_CLAIM = 'N' AND
        cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
),
DiagnosisNumbered AS (
    SELECT
        rc.CLAIM_HCC_ID,
        rc.CLAIM_STATUS,
        rc.CLAIM_TYPE_NAME,
        csc.CLAIM_SOURCE_NAME,
        rc.PRIMARY_DIAGNOSIS_CODE,
        CFD.DIAGNOSIS_CODE,
        ROW_NUMBER() OVER (PARTITION BY rc.CLAIM_FACT_KEY ORDER BY CFD.DIAGNOSIS_CODE) AS DIAGNOSIS_NUM
    FROM
        RecentClaims rc
    LEFT JOIN
        payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
    LEFT JOIN
        payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
    LEFT JOIN
        payor_dw.CLAIM_FACT_TO_DIAGNOSIS CFD ON rc.CLAIM_FACT_KEY = CFD.CLAIM_FACT_KEY
    WHERE
        rc.row_num = 1
        AND rc.CLAIM_STATUS IN ('Needs Review','Needs Repair')
  )
SELECT
    dn.CLAIM_HCC_ID,
    dn.CLAIM_STATUS,
    dn.CLAIM_TYPE_NAME,
    dn.CLAIM_SOURCE_NAME,
    --dn.PRIMARY_DIAGNOSIS_CODE,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 1 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE1,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 2 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE2,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 3 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE3,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 4 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE4,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 5 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE5,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 6 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE6,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 7 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE7,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 8 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE8,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 9 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE9,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 10 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE10,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 11 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE11,
    MAX(CASE WHEN dn.DIAGNOSIS_NUM = 11 THEN dn.DIAGNOSIS_CODE END) AS DIAGNOSIS_CODE12
FROM
    DiagnosisNumbered dn
GROUP BY
    dn.CLAIM_HCC_ID,
    dn.CLAIM_STATUS,
    dn.CLAIM_TYPE_NAME,
    dn.CLAIM_SOURCE_NAME,
    dn.PRIMARY_DIAGNOSIS_CODE;