    
    
 WITH RankedClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) AS rn
    FROM
        CLAIM_FACT cf
    WHERE
        cf.IS_CONVERTED = 'N'
        AND cf.IS_TRIAL_CLAIM = 'N'
        AND cf.IS_CURRENT = 'Y'
        --AND cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
SELECT
    ashf.SUPPLIER_NAME AS Supplier,
    SUM(CASE WHEN TO_CHAR(dd.DATE_VALUE, 'YYYY-MM') = '2024-07' THEN 1 ELSE 0 END) AS "2024-06(>=June-24)",
    SUM(CASE WHEN TO_CHAR(dd.DATE_VALUE, 'YYYY-MM') = '2024-07' THEN 1 ELSE 0 END) AS "2024-07(July)",
    SUM(CASE WHEN TO_CHAR(dd.DATE_VALUE, 'YYYY-MM') = '2024-08' THEN 1 ELSE 0 END) AS "2024-08(Aug)",
    SUM(CASE WHEN TO_CHAR(dd.DATE_VALUE, 'YYYY-MM') = '2024-09' THEN 1 ELSE 0 END) AS "2024-09(Sept)",
    COUNT(rc.CLAIM_HCC_ID) AS Total
FROM
    RankedClaims rc
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN
    payor_dw.SUPPLIER ASHF ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
WHERE
    rn = 1
    AND rc.CLAIM_STATUS = 'Denied'
    AND dd.DATE_VALUE >= TO_TIMESTAMP('2024-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    AND dd.DATE_VALUE < TO_TIMESTAMP('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
GROUP BY
    ashf.SUPPLIER_NAME
ORDER BY
    ashf.SUPPLIER_NAME;