WITH RecentClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) as row_num
    FROM
        payor_dw.claim_fact cf
    WHERE
        cf.IS_CONVERTED = 'N' AND
        cf.IS_TRIAL_CLAIM = 'N' AND
        cf.IS_CURRENT = 'Y' 
        --cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
SELECT 
    rc.ENTRY_TIME,
    dd.DATE_VALUE AS RECEIPT_DATE,
    --rc.MOST_RECENT_PROCESS_TIME,
    rc.CLAIM_CUR_HCC_ID,
    rc.CLAIM_HCC_ID,
    rc.EXTERNAL_CLAIM_BATCH_NUMBER,
    rc.EXTERNAL_CLAIM_NUMBER,
    rc.CLAIM_STATUS,
    rc.CLAIM_TYPE_NAME,
    csc.CLAIM_SOURCE_NAME,
    rrt.trigger_code AS REVIEW_TRIGGER,
    rrt.trigger_desc AS REVIEW_TRIGGER_DESC,
    rrt.TRIGGER_DOMAIN_NAME AS REVIEW_TRIGGER_DOMAIN,
    rrt.POLICY_NAME AS REVIEW_TRIGGER_POLICY_NAME,
    rrte.trigger_code AS EXCEPTION_TRIGGER,
    rrte.trigger_desc AS EXCEPTION_TRIGGER_DESC,
    rrte.TRIGGER_DOMAIN_NAME AS EXCEPTION_TRIGGER_DOMAIN,
    rrte.POLICY_NAME AS EXCEPTION_TRIGGER_POLICY_NAME,
    rc.SI_SUPPLIER_NAME,
    rc.SI_SUPPLIER_ADDRESS,
    rc.SI_SUPPLIER_CITY,
    rc.SI_SUPPLIER_STATE,
    rc.SI_SUPPLIER_ZIPCODE,
    al.AUDIT_LOG_ENTRY_FACT_KEY,
    --atc.ACTION_TYPE_DESC,
    al.CLIENT_IP_ADDRESS,
    al.LOG_NOTE,
    al.MESSAGE_DESC,
    al.MESSAGE_DOMAIN_NAME,
    al.SERVER_NAME,
    al.SUBTYPE_NM,
    al.TRANSACTION_FACT_KEY,
    ua.FULL_NAME AS CLAIM_SUBMITTED_USER,
    d.DIAGNOSIS_CODE,
    d.DIAGNOSIS_LONG_DESC AS DIAGNOSIS_DESC,
    rc.FACILITY_LOCATION_NAME,
    m.MEMBER_FULL_NAME,
    m.MEMBER_HOME_ADDRESS_KEY,
    m.TELEPHONE_NUMBER,
    m.MEMBER_GENDER_CODE,
    rc.SUBMITTER_NM AS SUBMITTED_BY,
    rc.CLAIM_LEVEL_SUBMITTED_CHARGES AS BILLED_AMOUNT,
    rc.IS_ADJUSTED,
    rc.IS_AUTO_ACCIDENT,
    rc.IS_CURRENT,
    rc.IS_EMPLOYMENT_ACCIDENT,
    rc.IS_FIRST_PASS_AUTO_ADJUDICATED,
    rc.IS_FIRST_PASS_REPAIRED,
    rc.IS_FIRST_PASS_REVIEWED,
    rc.IS_OTHER_ACCIDENT,
    rc.IS_RENEWED,
    rc.IS_REPLACEMENT_OF_PROSTHESIS,
    rc.IS_TREATMENT_FOR_ORTHODONTICS,
    rc.IS_VOIDED,
    rc.IS_BLUECARD_ADJUSTMENT,
    rc.IS_POST_PAY_RECOVERY
FROM
    RecentClaims rc
LEFT JOIN
    payor_dw.CLAIM_FACT_TO_REVIEW_TRIGGER cftrt ON rc.CLAIM_FACT_KEY = cftrt.CLAIM_FACT_KEY
LEFT JOIN
    payor_dw.review_repair_trigger rrt ON cftrt.REVIEW_REPAIR_TRIGGER_KEY = rrt.REVIEW_REPAIR_TRIGGER_KEY
LEFT JOIN
    payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
LEFT JOIN
    payor_dw.AUDIT_LOG_ENTRY_FACT al ON rc.AUDIT_LOG_KEY = al.AUDIT_LOG_KEY
LEFT JOIN
    payor_dw.USER_ACCOUNT ua ON al.HCC_USER_ID = ua.USER_ACCOUNT_KEY
LEFT JOIN
    payor_dw.DIAGNOSIS d ON rc.PRIMARY_DIAGNOSIS_CODE = d.DIAGNOSIS_CODE
LEFT JOIN
    payor_dw.ACTION_TYPE_CODE atc ON al.ACTION_TYPE_CODE = atc.ACTION_TYPE_CODE
LEFT JOIN
    payor_dw.MEMBER m ON rc.MEMBER_KEY = m.MEMBER_KEY
LEFT JOIN
    payor_dw.CLAIM_FACT_TO_EXCEPTION cfte ON rc.CLAIM_FACT_KEY = cfte.CLAIM_FACT_KEY
LEFT JOIN
    payor_dw.review_repair_trigger rrte ON cfte.REVIEW_REPAIR_TRIGGER_KEY = rrte.REVIEW_REPAIR_TRIGGER_KEY
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
WHERE
    rc.row_num = 1
   --AND rc.CLAIM_HCC_ID IS NULL;