SELECT SNHF.SUPPLIER_NETWORK_HCC_ID,
SNHF.SUPPLIER_NETWORK_NAME, 
S.SUPPLIER_HCC_ID, 
s.supplier_status,
S.supplier_name,S.SUPPLIER_NPI,
SL.SUPPLIER_LOCATION_HCC_ID,
SL.SUPPLIER_LOCATION_NAME,
SL.Supplier_location_status,
SL.SUPPLIER_LOCATION_NPI
FROM [HealthEdge_Prod_Copy].[dbo].[SUPPLIER_TO_SUPPLIER_NETWORK] STSN
JOIN [HealthEdge_Prod_Copy].[dbo].[SUPPLIER] S ON STSN.supplier_key = S.supplier_key
JOIN [HealthEdge_Prod_Copy].[dbo].[SUPPLIER_LOCATION] SL ON S.supplier_key = SL.supplier_key
JOIN [HealthEdge_Prod_Copy].[dbo].[SUPPLIER_NETWORK_HISTORY_FACT] SNHF ON STSN.SUPPLIER_NETWORK_KEY = SNHF.SUPPLIER_NETWORK_KEY
WHERE SNHF.SUPPLIER_NETWORK_HCC_ID ='SN0017';