SELECT
        s.SUPPLIER_HCC_ID ,
        s.SUPPLIER_NPI ,
        s.SUPPLIER_NAME ,
        s.SUPPLIER_KEY ,
        s.SUPPLIER_HISTORY_FACT_KEY ,
--        s.TAX_ID ,
--        s.TAX_NAME ,
        rtc.REMITTANCE_TYPE_CODE ,
        rtc.REMITTANCE_TYPE_DESC ,
        soi.IDENTIFICATION_NUMBER ,
        itc.ID_TYPE_KEY ,
        itc.ID_TYPE_CODE ,
        itc.ID_TYPE_DESC ,
        itc.ID_TYPE_NAME
FROM supplier s
JOIN REMITTANCE_TYPE_CODE RTC ON s.REMITTANCE_TYPE_KEY = rtc.REMITTANCE_TYPE_KEY
JOIN SUPPLIER_OTHER_ID soi ON s.SUPPLIER_HISTORY_FACT_KEY = soi.SUPPLIER_HISTORY_FACT_KEY
JOIN ID_TYPE_CODE itc ON soi.ID_TYPE_KEY =itc.ID_TYPE_KEY
--JOIN VERSION_EFF_DATE_KEY effDT
--JOIN VERSION_EXP_DATE_KEY
WHERE s.SUPPLIER_HCC_ID = '1004673'
--s.SUPPLIER_HCC_ID = '33256'
--s.SUPPLIER_HCC_ID = '15855'