-- PRACTITIONER_HCC_ID, PRACTITIONER_FIRST_NAME, PRACTITIONER_LAST_NAME, PRACTITIONER_FULL_NAME, PRACTITIONER_NPI,
   
SELECT * FROM ALL_PRACTITIONER_HISTORY_FACT aphf    -- 50,062

SELECT * FROM PRACTITIONER_HISTORY_FACT phf         -- 50,062

SELECT * FROM PRACTITIONER p                        -- 49,986


SELECT * 
FROM 
  ALL_PRACTITIONER_HISTORY_FACT aphf, 
  DATE_DIMENSION effDt, 
  DATE_DIMENSION expDt 
WHERE 
  effDt.DATE_KEY = aphf.VERSION_EFF_DATE_KEY 
  and expDt.DATE_KEY = aphf.VERSION_EXP_DATE_KEY 
  and effDt.DATE_VALUE <= SYSDATE 
  and expDt.DATE_VALUE > SYSDATE;
 --49,986