WITH RecentClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) as row_num
    FROM
        payor_dw.claim_fact cf
    WHERE
        cf.IS_CONVERTED = 'N' AND
        cf.IS_TRIAL_CLAIM = 'N' AND
        cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
--AggregatedClaimLines AS (
--    SELECT
--        CLAIM_FACT_KEY,
--        SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
--        SUM(PAID_AMOUNT) AS TOTAL_PAID_AMOUNT
--    FROM
--        payor_dw.ALL_CLAIM_LINE_FACT
--    GROUP BY
--        CLAIM_FACT_KEY
--)
SELECT 
    rc.CLAIM_HCC_ID,
    rc.CLAIM_STATUS,
    aclf.CLAIM_LINE_HCC_ID ,
    clrrte.trigger_code AS Claim_Line_Exception_Trigger,  
    clrrte.trigger_desc AS Claim_Line_Exception_Trigger_desc,
--    clrrte.TRIGGER_DOMAIN_NAME AS Claim_Line_Exception_Trigger_Domain,
--    clrrte.POLICY_NAME AS Claim_Line_Exception_Trigger_Policy_Name,
    aclf.PLACE_OF_SERVICE_CODE,
    aclf.SI_ORDERING_PRACT_NPI,
    aclf.SI_ORDERING_PRACT_FNAME,
    pt.PROVIDER_TAXONOMY_NAME ,
    dd.DATE_VALUE AS RECEIPT_DATE,
    TRUNC(CURRENT_DATE) -  TRUNC(dd.DATE_VALUE) AS day_difference_receipt,
    rc.SI_SUPPLIER_NAME AS SUBMITTED_SUPPLIER_NAME,
    ashf.SUPPLIER_NAME AS ASHF_SUPPLIER_NAME,
    rc.SI_SUPPLIER_NPI AS SUBMITTED_SUPPLIER_NPI,
    ashf.SUPPLIER_NPI  AS ASHF_SUPPLIER_NPI,
    rc.SI_SUPPLIER_ID AS SUBMITTED_SUPPLIER_ID,
    ashf.SUPPLIER_HCC_ID AS ASHF_SUPPLIER_HCC_ID,
    rc.SI_SUPPLIER_TAX AS SUBMITTED_SUPPLIER_TAX,
    TE.TAX_ID AS ASHF_TAX_ID,
    rc.FACILITY_LOCATION_ID AS SUBMITTED_LOCATION_ID,
    sl.SUPPLIER_LOCATION_HCC_ID ,
    rc.FACILITY_LOCATION_NAME AS SUBMITTED_LOCATION_NAME,
    sl.SUPPLIER_LOCATION_NAME ,
    rc.FACILITY_LOCATION_NPI AS SUBMITTED_LOCATION_NPI,
    sl.SUPPLIER_LOCATION_NPI ,
    --p.PRACTITIONER_HCC_ID ,
    --p.PRACTITIONER_FIRST_NAME ,
    --am.ADJUDICATION_MESSAGE_CODE AS Message_Code, 
    --am.ADJUDICATION_MESSAGE_DESC AS MESSAGE_DESC, 
    rc.SI_SUPPLIER_ADDRESS AS SUBMITTED_SUPPLIER_ADDRESS,
    rc.SI_SUPPLIER_CITY AS SUBMITTED_SUPPLIER_CITY,
    rc.SI_SUPPLIER_STATE AS SUBMITTED_SUPPLIER_STATE,
    rc.SI_SUPPLIER_ZIPCODE AS SUBMITTED_SUPPLIER_ZIPCODE,
    PA.ADDRESS_LINE AS ASHF_SUPPLIER_ADDRESS,
    PA.CITY_NAME AS ASHF_SUPPLIER_CITY,
    PA.STATE_CODE AS ASHF_SUPPLIER_STATE ,
    PA.ZIP_CODE AS ASHF_SUPPLIER_ZIPCODE,
    rc.ENTRY_TIME,
    rc.MOST_RECENT_PROCESS_TIME 
FROM
    RecentClaims rc
--LEFT JOIN
--    AggregatedClaimLines aclf_agg ON rc.CLAIM_FACT_KEY = aclf_agg.CLAIM_FACT_KEY
LEFT JOIN
     payor_dw.ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY
LEFT JOIN
    PAYOR_DW.CLAIM_LINE_FACT_TO_EXCEPTION clfe ON aclf.CLAIM_LINE_FACT_KEY = clfe.CLAIM_LINE_FACT_KEY
LEFT JOIN
    payor_dw.review_repair_trigger clrrte ON clfe.REVIEW_REPAIR_TRIGGER_KEY= clrrte.REVIEW_REPAIR_TRIGGER_KEY
LEFT JOIN
    payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN
	payor_dw.supplier ashf ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
LEFT JOIN
	payor_dw.POSTAL_ADDRESS pa ON ASHF.SUPPLIER_CORR_ADDRESS_KEY = pa.POSTAL_ADDRESS_KEY 
LEFT JOIN 
	payor_dw.SUPPLIER_LOCATION sl ON rc.LOCATION_KEY = sl.SUPPLIER_LOCATION_KEY 
LEFT JOIN 
	payor_dw.TAX_ENTITY te ON ASHF.TAX_ENTITY_KEY = TE.TAX_ENTITY_KEY 
LEFT JOIN
	payor_dw.PROVIDER_TAXONOMY pt ON ashf.PRIMARY_CLASSIFICATION_KEY = pt.PROVIDER_TAXONOMY_KEY
--LEFT JOIN 
	--payor_dw.PRACTITIONER p ON aclf.PRACTITIONER_KEY = p.PRACTITIONER_KEY 
--LEFT JOIN 
    --payor_dw.CLAIM_LINE_FACT_TO_ADJD_MSG clfam ON aclf.CLAIM_LINE_FACT_KEY = clfam.CLAIM_LINE_FACT_KEY 
--LEFT JOIN 
    --payor_dw.ADJUDICATION_MESSAGE am ON clfam.ADJUDICATION_MESSAGE_KEY = am.ADJUDICATION_MESSAGE_KEY 
WHERE
    rc.CLAIM_STATUS IN ('Needs Repair', 'Needs Review') AND 
    clrrte.trigger_code ='196' AND
    rc.row_num = 1  