-----------------------------------------------------------------------------------------------------------------------------------
 --Version -1
-----------------------------------------------------------------------------------------------------------------------------------
WITH RankedClaims AS (
    SELECT
  cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) AS rn
    FROM
        CLAIM_FACT cf
    WHERE
        cf.IS_CONVERTED = 'N'
        AND cf.IS_TRIAL_CLAIM = 'N'
--        AND cf.IS_CURRENT = 'Y'  
)
--AggregatedClaimLines AS (
--    SELECT
--        aclf.CLAIM_FACT_KEY,
--        SUM(aclf.BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
--        SUM(aclf.PAID_AMOUNT) AS TOTAL_PAID_AMOUNT
--    FROM
--        payor_dw.ALL_CLAIM_LINE_FACT aclf
--    GROUP BY
--        aclf.CLAIM_FACT_KEY
--)
SELECT
	rc.CLAIM_FACT_KEY,
    rc.CLAIM_HCC_ID,
--    rc.CLAIM_STATUS,
--    rc.CLAIM_TYPE_NAME,
    csc.CLAIM_SOURCE_NAME,
    dd.DATE_VALUE AS Receipt_Date,
    rc.ENTRY_TIME,
    rc.MOST_RECENT_PROCESS_TIME ,
    aclf.CLAIM_LINE_HCC_ID ,
--    aclf_agg.TOTAL_BILLED_AMOUNT,
--    aclf_agg.TOTAL_PAID_AMOUNT,
	aclf.BILLED_AMOUNT,
	aclf.PAID_AMOUNT,
    cpf.PAYABLE_AMOUNT AS pf_claim_paid,
    cif.INTEREST_AMOUNT as pf_Interest_amount,
--    (cpf.PAYABLE_AMOUNT + cif.INTEREST_AMOUNT) AS pf_final_paid_amount,
    rf.ORIG_RECEIVABLE_AMOUNT ,
--    rrf.RECEIVED_AMOUNT,
    cpf.RESULTED_IN_RECEIVABLE,
    claimpaydate.DATE_VALUE AS pf_claim_transaction_date,
    pf.PAYMENT_NUMBER AS CHECK_NUMBER,
    suppaydate.DATE_VALUE AS CHECK_PAYMENT_DATE,
    pf.PAYMENT_AMOUNT AS CHECK_PAID_Amount,
--    pf.PAY_TO_NAME AS Payee_Name,
--    pf.PAYMENT_CYCLE_KEY AS Payment_Cycle_ID,
    pf.PAYMENT_FACT_KEY AS Payment_Transaction_Num,
    pf.PAYMENT_BATCH_KEY AS Payment_Batch_ID
FROM RankedClaims rc
--LEFT JOIN
--    AggregatedClaimLines aclf_agg ON rc.CLAIM_FACT_KEY = aclf_agg.CLAIM_FACT_KEY
LEFT JOIN
	payor_dw.ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY
LEFT JOIN
    payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
LEFT JOIN
	payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN
	payor_dw.SUPPLIER ASHF ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
LEFT JOIN
  	payor_dw.CLAIM_PAYABLE_FACT cpf ON aclf.CLAIM_LINE_FACT_KEY = cpf.CLAIM_LINE_FACT_KEY
LEFT JOIN
 	payor_dw.PMT_FACT_TO_CLM_PAYABLE_FACT pfcpf ON cpf.CLAIM_PAYABLE_FACT_KEY = pfcpf.CLAIM_PAYABLE_FACT_KEY
LEFT JOIN
	payor_dw.PAYMENT_FACT pf ON pfcpf.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
--LEFT JOIN
--	payor_dw.CLAIM_INTEREST_FACT cif ON aclf.CLAIM_LINE_FACT_KEY = cif.CLAIM_LINE_FACT_KEY
LEFT JOIN
	payor_dw.CLAIM_INTRST_FCT_TO_CLM_PAYBLE ciftcp ON cpf.CLAIM_PAYABLE_FACT_KEY = ciftcp.CLAIM_PAYABLE_FACT_KEY
LEFT JOIN
	payor_dw.CLAIM_INTEREST_FACT cif ON cif.CLAIM_INTEREST_FACT_KEY  = ciftcp.CLAIM_INTEREST_FACT_KEY
LEFT JOIN
	payor_dw.RECV_TO_POS_CLAIM_PAYABLE_FACT rtpcpf ON cpf.CLAIM_PAYABLE_FACT_KEY = rtpcpf.CLAIM_PAYABLE_FACT_KEY
LEFT JOIN
	payor_dw.RECEIVABLE_FACT rf ON rtpcpf.RECV_FACT_KEY = rf.RECEIVABLE_FACT_KEY
LEFT JOIN
	payor_dw.RECV_TO_NEG_CLAIM_PAYABLE_FACT rtncpf ON cpf.CLAIM_PAYABLE_FACT_KEY =  rtncpf.CLAIM_PAYABLE_FACT_KEY
LEFT JOIN
	payor_dw.RECEIVABLE_FACT rf ON rtncpf.RECV_FACT_KEY = rf.RECEIVABLE_FACT_KEY
--LEFT JOIN
--	payor_dw.RECEIVABLE_FACT rf ON cpf.CLAIM_PAYABLE_FACT_KEY = rf.CLAIM_PAYABLE_FACT_KEY
--LEFT JOIN
--	payor_dw.RECV_TO_POS_CLAIM_PAYABLE_FACT rtpcpf ON rf.RECEIVABLE_FACT_KEY = rtpcpf.RECV_FACT_KEY
--LEFT JOIN
--	payor_dw.RECEIVABLE_FACT rf ON rtncpf.RECV_FACT_KEY = rf.RECEIVABLE_FACT_KEY
--LEFT JOIN
--	payor_dw.RECV_TO_NEG_CLAIM_PAYABLE_FACT rtncpf ON cpf.CLAIM_PAYABLE_FACT_KEY =  rtncpf.CLAIM_PAYABLE_FACT_KEY
LEFT JOIN
	payor_dw.DATE_DIMENSION suppaydate ON pf.PAYMENT_DATE_KEY = suppaydate.DATE_KEY
LEFT JOIN
	payor_dw.DATE_DIMENSION claimpaydate ON cpf.PAYABLE_DATE_KEY = claimpaydate.DATE_KEY
--LEFT JOIN 	
--	payor_dw.RECEIVABLE_RECOUPMENT_FACT rrf ON cpf.CLAIM_PAYABLE_FACT_KEY  = rrf.CLAIM_PAYABLE_FACT_KEY  --(25.59)(W)  6.99(F)
--LEFT JOIN
--	payor_dw.RECEIVABLE_FACT rf ON rrf.RECEIVABLE_RECOUPMENT_FACT_KEY = rf.RECEIVABLE_RECOUPMENT_FACT_KEY --(25.59)(W) 6.99(F)
--LEFT JOIN
--	payor_dw.RECEIVABLE_FACT rf ON rrf.RECEIVABLE_FACT_KEY = rf.RECEIVABLE_FACT_KEY  --(25.59)(wrong) 6.99(Fail)
WHERE
 rc.CLAIM_HCC_ID = '2024235003300' --(receivable, recoipment)(both at same transaction )
--	rc.CLAIM_HCC_ID = '2024314000853'
	--rc.CLAIM_HCC_ID ='2024159000517'
  -- rc.CLAIM_HCC_ID = '2024191001199' --(receivable, recoupment)(recoupment missing at diff transaction)
--	AND rc.rn = 1
	AND suppaydate.DATE_VALUE IS NOT NULL
ORDER BY
	suppaydate.DATE_VALUE, aclf.CLAIM_LINE_HCC_ID

-----------------------------------------------------------------------------------------------------------------------------------
 --Version -2
-----------------------------------------------------------------------------------------------------------------------------------

WITH Recoup_CTE AS (
  SELECT orf.PAYMENT_FACT_KEY, cf.CLAIM_HCC_ID, clf.claim_line_hcc_id, clf.original_line_number, 
         SUM(rrf.RECEIVED_AMOUNT) received_amount
  FROM OFFSET_RECEIVABLE_FACT orf
  JOIN OFFSET_REC_TO_REC_RECOUP_FACT ortrrf ON ortrrf.OFFSET_RECEIVABLE_FACT_KEY = orf.OFFSET_RECEIVABLE_FACT_KEY
  JOIN RECEIVABLE_RECOUPMENT_FACT rrf ON rrf.RECEIVABLE_RECOUPMENT_FACT_KEY = ortrrf.RECEIVABLE_RECOUPMENT_FACT_KEY
  JOIN CLAIM_FACT cf ON cf.CLAIM_FACT_KEY = rrf.CLAIM_FACT_KEY
  JOIN CLAIM_LINE_FACT clf ON clf.CLAIM_FACT_KEY = cf.CLAIM_FACT_KEY
  --AND clf.ORIGINAL_LINE_NUMBER = ortrrf.ORIGINAL_LINE_NUMBER
  GROUP BY orf.PAYMENT_FACT_KEY, cf.CLAIM_HCC_ID, clf.claim_line_hcc_id, clf.original_line_number
),
Receivable_CTE AS (
  SELECT orf.PAYMENT_FACT_KEY, rf.CLAIM_HCC_ID, rf.CLAIM_LINE_HCC_ID, 
         SUM(ORIG_RECEIVABLE_AMOUNT) ORIG_RECEIVABLE_AMOUNT, 
         COALESCE(SUM(cif.INTEREST_AMOUNT), 0) RECOUP_INTEREST
  FROM OFFSET_RECEIVABLE_FACT orf
  LEFT JOIN RECEIVABLE_FACT rf ON rf.RECEIVABLE_FACT_KEY = orf.RECEIVABLE_FACT_KEY 
                               AND rf.CLAIM_FACT_KEY IS NOT NULL AND rf.CLAIM_LINE_FACT_KEY IS NOT NULL
  LEFT JOIN CLAIM_INTEREST_FACT cif ON rf.CLAIM_FACT_KEY = cif.CLAIM_FACT_KEY 
                                    AND rf.CLAIM_LINE_FACT_KEY = cif.CLAIM_LINE_FACT_KEY 
                                    AND cif.RESULTED_IN_RECEIVABLE = 'Y' 
                                    AND cif.IS_VOID != 'Y'
  GROUP BY orf.PAYMENT_FACT_KEY, rf.CLAIM_HCC_ID, rf.CLAIM_LINE_HCC_ID
),
Interest_CTE AS (
  SELECT cf.CLAIM_HCC_ID, clf.claim_line_hcc_id, clf.original_line_number, pf.PAYMENT_FACT_KEY, 
         SUM(cif.INTEREST_AMOUNT) INTEREST_AMOUNT, 
         SUM(lhpf.payable_amount) INT_WITHHOLD_AMOUNT
  FROM PAYMENT_FACT pf
  JOIN PMT_FACT_TO_CLM_INT_FACT pftcif ON pftcif.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
  JOIN CLAIM_INTEREST_FACT cif ON cif.CLAIM_INTEREST_FACT_KEY = pftcif.INTEREST_PAYMENT_FACT_KEY
  LEFT JOIN LIEN_HOLDER_PAYABLE_FACT lhpf ON lhpf.PAYABLE_KEY = cif.CLAIM_INTEREST_FACT_KEY
  JOIN CLAIM_FACT cf ON cf.CLAIM_FACT_KEY = cif.CLAIM_FACT_KEY
  JOIN CLAIM_LINE_FACT clf ON clf.CLAIM_LINE_FACT_KEY = cif.CLAIM_LINE_FACT_KEY
  GROUP BY cf.CLAIM_HCC_ID, clf.claim_line_hcc_id, clf.original_line_number, pf.PAYMENT_FACT_KEY
)
SELECT
  pf.PAYMENT_FACT_KEY, pf.PAYMENT_NUMBER, 'Claim' AS PAYABLE_TYPE, cf.CLAIM_HCC_ID, 
  clf.claim_line_hcc_id, clf.original_line_number, pf.SUPPLIER_KEY, 
  pf.SUPPLIER_LOCATION_KEY, pf.MEMBER_KEY, pf.PAYEE_TYPE_NAME, pf.PAYMENT_CYCLE_KEY, 
  pf.PAY_TO_NAME, pf.BANK_ACCOUNT_KEY, payment_dt.DATE_VALUE AS PAYMENT_DATE, 
  psc.PAYMENT_STATUS_DESC, 
  SUM(COALESCE(cpf.PAYABLE_AMOUNT, 0)) AS PAYABLE_AMOUNT, 
  0 AS MANUAL_PAYABLE, 
  COALESCE(interest.INTEREST_AMOUNT, 0) AS INTEREST_AMOUNT, 
  COALESCE(receivable.ORIG_RECEIVABLE_AMOUNT, 0) AS RECEIVABLE_AMOUNT, 
  COALESCE(recoup.RECEIVED_AMOUNT, 0) AS APPLIED_TO_RECEIVABLES, 
  SUM(COALESCE(lien.PAYABLE_AMOUNT, 0)) + SUM(COALESCE(interest.INT_WITHHOLD_AMOUNT, 0)) AS WITHHOLD_AMOUNT,
  SUM(COALESCE(cpf.PAYABLE_AMOUNT, 0)) + COALESCE(interest.INTEREST_AMOUNT, 0) + 
  COALESCE(receivable.ORIG_RECEIVABLE_AMOUNT, 0) - COALESCE(recoup.RECEIVED_AMOUNT, 0) - 
  SUM(COALESCE(lien.PAYABLE_AMOUNT, 0)) - SUM(COALESCE(interest.INT_WITHHOLD_AMOUNT, 0)) AS PAYMENT_AMOUNT
FROM PAYMENT_FACT pf
JOIN PAYMENT_STATUS_CODE psc ON psc.PAYMENT_STATUS_CODE = pf.PAYMENT_STATUS_CODE
JOIN PMT_FACT_TO_CLM_PAYABLE_FACT pftcpf ON pftcpf.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
JOIN CLAIM_PAYABLE_FACT cpf ON cpf.CLAIM_PAYABLE_FACT_KEY = pftcpf.CLAIM_PAYABLE_FACT_KEY
JOIN CLAIM_LINE_FACT clf ON clf.CLAIM_LINE_FACT_KEY = cpf.CLAIM_LINE_FACT_KEY
JOIN CLAIM_FACT cf ON cf.CLAIM_FACT_KEY = clf.CLAIM_FACT_KEY
JOIN DATE_DIMENSION payment_dt ON payment_dt.DATE_KEY = pf.PAYMENT_DATE_KEY
LEFT JOIN Recoup_CTE recoup ON recoup.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY 
  AND recoup.CLAIM_HCC_ID = cf.CLAIM_HCC_ID AND recoup.claim_line_hcc_id = clf.claim_line_hcc_id
LEFT JOIN Receivable_CTE receivable ON receivable.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
LEFT JOIN Interest_CTE interest ON interest.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
LEFT JOIN (
  SELECT PAYABLE_KEY, SUM(PAYABLE_AMOUNT) PAYABLE_AMOUNT
  FROM LIEN_HOLDER_PAYABLE_FACT
  GROUP BY PAYABLE_KEY
) lien ON lien.PAYABLE_KEY = cpf.CLAIM_PAYABLE_FACT_KEY
WHERE 
--pf.PAYMENT_STATUS_CODE IN ('1', '3')
-- payment_dt.DATE_VALUE >= TO_TIMESTAMP('2024-07-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
--AND payment_dt.DATE_VALUE < TO_TIMESTAMP('2024-07-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
----AND pf.PAYMENT_NUMBER = '447'
--AND pf.PAYMENT_NUMBER IN  ('477','478','479','480','481','482','483','484','485','486')
 cf.CLAIM_HCC_ID = '2024207013360'
GROUP BY pf.PAYMENT_FACT_KEY, pf.PAYMENT_NUMBER, cf.CLAIM_HCC_ID, clf.claim_line_hcc_id, clf.original_line_number,
  pf.SUPPLIER_KEY, pf.SUPPLIER_LOCATION_KEY, pf.MEMBER_KEY, pf.PAYEE_TYPE_NAME, 
  pf.PAYMENT_CYCLE_KEY, pf.PAY_TO_NAME, pf.BANK_ACCOUNT_KEY, payment_dt.DATE_VALUE, 
  psc.PAYMENT_STATUS_DESC, receivable.ORIG_RECEIVABLE_AMOUNT, receivable.RECOUP_INTEREST, 
  recoup.RECEIVED_AMOUNT, interest.INTEREST_AMOUNT;
-----------------------------------------------------------------------------------------------------------------------------------
 --Version -3
-----------------------------------------------------------------------------------------------------------------------------------

 
WITH Recoup_CTE AS (
  SELECT 
    orf.PAYMENT_FACT_KEY, 
    SUM(rrf.RECEIVED_AMOUNT) received_amount
  FROM OFFSET_RECEIVABLE_FACT orf
  JOIN OFFSET_REC_TO_REC_RECOUP_FACT ortrrf 
    ON ortrrf.OFFSET_RECEIVABLE_FACT_KEY = orf.OFFSET_RECEIVABLE_FACT_KEY
  JOIN RECEIVABLE_RECOUPMENT_FACT rrf 
    ON rrf.RECEIVABLE_RECOUPMENT_FACT_KEY = ortrrf.RECEIVABLE_RECOUPMENT_FACT_KEY
  GROUP BY orf.PAYMENT_FACT_KEY
),
Receivable_CTE AS (
  SELECT 
    orf.PAYMENT_FACT_KEY, 
    SUM(rf.ORIG_RECEIVABLE_AMOUNT) ORIG_RECEIVABLE_AMOUNT
  FROM OFFSET_RECEIVABLE_FACT orf
  JOIN RECEIVABLE_FACT rf 
    ON rf.RECEIVABLE_FACT_KEY = orf.RECEIVABLE_FACT_KEY
  GROUP BY orf.PAYMENT_FACT_KEY
),
Interest_CTE AS (
  SELECT 
    pf.PAYMENT_FACT_KEY, 
    SUM(cif.INTEREST_AMOUNT) INTEREST_AMOUNT, 
    SUM(lhpf.PAYABLE_AMOUNT) INT_WITHHOLD_AMOUNT
  FROM PAYMENT_FACT pf
  JOIN PMT_FACT_TO_CLM_INT_FACT pftcif 
    ON pftcif.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
  JOIN CLAIM_INTEREST_FACT cif 
    ON cif.CLAIM_INTEREST_FACT_KEY = pftcif.INTEREST_PAYMENT_FACT_KEY
  LEFT JOIN LIEN_HOLDER_PAYABLE_FACT lhpf 
    ON lhpf.PAYABLE_KEY = cif.CLAIM_INTEREST_FACT_KEY
  GROUP BY pf.PAYMENT_FACT_KEY
)
SELECT
  SUM(COALESCE(cpf.PAYABLE_AMOUNT, 0)) AS PAYABLE_AMOUNT, 
  0 AS MANUAL_PAYABLE, 
  COALESCE(SUM(interest.INTEREST_AMOUNT), 0) AS INTEREST_AMOUNT, 
  COALESCE(SUM(receivable.ORIG_RECEIVABLE_AMOUNT), 0) AS RECEIVABLE_AMOUNT, 
  COALESCE(SUM(recoup.RECEIVED_AMOUNT), 0) AS APPLIED_TO_RECEIVABLES, 
  COALESCE(SUM(lien.PAYABLE_AMOUNT), 0) + 
  COALESCE(SUM(interest.INT_WITHHOLD_AMOUNT), 0) AS WITHHOLD_AMOUNT,
  SUM(COALESCE(cpf.PAYABLE_AMOUNT, 0)) + 
  COALESCE(SUM(interest.INTEREST_AMOUNT), 0) + 
  COALESCE(SUM(receivable.ORIG_RECEIVABLE_AMOUNT), 0) - 
  COALESCE(SUM(recoup.RECEIVED_AMOUNT), 0) - 
  COALESCE(SUM(lien.PAYABLE_AMOUNT), 0) - 
  COALESCE(SUM(interest.INT_WITHHOLD_AMOUNT), 0) AS PAYMENT_AMOUNT
FROM PAYMENT_FACT pf
JOIN PAYMENT_STATUS_CODE psc 
  ON psc.PAYMENT_STATUS_CODE = pf.PAYMENT_STATUS_CODE
JOIN PMT_FACT_TO_CLM_PAYABLE_FACT pftcpf 
  ON pftcpf.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
JOIN CLAIM_PAYABLE_FACT cpf 
  ON cpf.CLAIM_PAYABLE_FACT_KEY = pftcpf.CLAIM_PAYABLE_FACT_KEY
JOIN DATE_DIMENSION payment_dt 
  ON payment_dt.DATE_KEY = pf.PAYMENT_DATE_KEY
LEFT JOIN Recoup_CTE recoup 
  ON recoup.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
LEFT JOIN Receivable_CTE receivable 
  ON receivable.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
LEFT JOIN Interest_CTE interest 
  ON interest.PAYMENT_FACT_KEY = pf.PAYMENT_FACT_KEY
LEFT JOIN (
  SELECT PAYABLE_KEY, SUM(PAYABLE_AMOUNT) PAYABLE_AMOUNT
  FROM LIEN_HOLDER_PAYABLE_FACT
  GROUP BY PAYABLE_KEY
) lien 
  ON lien.PAYABLE_KEY = cpf.CLAIM_PAYABLE_FACT_KEY
WHERE 
--payment_dt.DATE_VALUE >= TO_TIMESTAMP('2024-07-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
--  AND payment_dt.DATE_VALUE < TO_TIMESTAMP('2024-07-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
-- AND pf.PAYMENT_NUMBER IN ('477','478','479','480','481','482','483','484','485','486')
 '2024207013360'

SELECT * FROM payments p WHERE p.CLAIM_HCC_ID = '2024207013360'