WITH RecentClaims AS (
    SELECT
        cf.*,
        ROW_NUMBER() OVER (PARTITION BY cf.CLAIM_HCC_ID ORDER BY cf.MOST_RECENT_PROCESS_TIME DESC) as row_num
    FROM
        payor_dw.claim_fact cf
    WHERE
        cf.IS_CONVERTED = 'N' AND
        cf.IS_TRIAL_CLAIM = 'N' AND 
        cf.IS_CURRENT = 'Y' AND 
        cf.ENTRY_TIME >= TO_TIMESTAMP('2024-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
)
SELECT DISTINCT  
    rc.CLAIM_HCC_ID,
--	aclf.CLAIM_LINE_HCC_ID,
    rc.CLAIM_STATUS,
    rc.CLAIM_TYPE_NAME,
    csc.CLAIM_SOURCE_NAME,
    rc.SUBMITTED_SUBSCRIBER_ID,
--    dt_st.DATE_VALUE AS SERVICE_START_DATE,
--    dt_end.DATE_VALUE AS SERVICE_END_DATE,
--    EF.flag_action,
--    EF.flag_message,
--    EF.flag_mnemonic,
--    aclf.SERVICE_CODE,
--    LISTAGG(DISTINCT CLFD.DIAGNOSIS_CODE, ', ') WITHIN GROUP (ORDER BY CLFD.DIAGNOSIS_CODE) AS DIAGNOSIS_CODES,
    RRT.TRIGGER_DESC,
    rc.SI_SUPPLIER_NPI,
    ashf.SUPPLIER_NPI  AS ASHF_SUPPLIER_NPI,
    RC.SI_SUPPLIER_ID,
    ashf.SUPPLIER_HCC_ID AS ASHF_SUPPLIER_HCC_ID,
    rc.SI_SUPPLIER_NAME,
    ashf.SUPPLIER_NAME AS ASHF_SUPPLIER_NAME,
    rc.SI_SUPPLIER_ADDRESS,
    rc.SI_SUPPLIER_CITY,
    rc.SI_SUPPLIER_STATE,
    rc.SI_SUPPLIER_COUNTRY,
    rc.SI_SUPPLIER_ZIPCODE,
    PA.ADDRESS_LINE AS ASHF_SUPPLIER_ADDRESS,
    PA.CITY_NAME AS ASHF_SUPPLIER_CITY,
    PA.STATE_CODE AS ASHF_SUPPLIER_STATE,
    PA.COUNTY_CODE AS ASHF_SUPPLIER_COUNTRY,
    PA.ZIP_CODE AS ASHF_SUPPLIER_ZIPCODE,
    dd.DATE_VALUE AS RECEIPT_DATE,
    TRUNC(CURRENT_DATE) - TRUNC(dd.DATE_VALUE) AS Claim_Aging,
    rc.MOST_RECENT_PROCESS_TIME
FROM
    RecentClaims rc
LEFT JOIN
    payor_dw.CLAIM_SOURCE_CODE csc ON rc.CLAIM_SOURCE_KEY = csc.CLAIM_SOURCE_KEY
LEFT JOIN
    payor_dw.ALL_CLAIM_LINE_FACT aclf ON rc.CLAIM_FACT_KEY = aclf.CLAIM_FACT_KEY
LEFT JOIN 
    payor_dw.CLAIM_LN_FCT_TO_EXT_RES clfer ON aclf.CLAIM_LINE_FACT_KEY = clfer.CLAIM_LINE_FACT_KEY
LEFT JOIN 
    payor_dw.EXT_EDITOR_CLM_LN_RES_TO_FLAGS EECLRF ON clfer.EXT_EDITOR_CLM_LN_RESULT_KEY = eeclrf.EXT_EDITOR_CLM_LN_RESULT_KEY
LEFT JOIN 
    payor_dw.EDIT_FLAG EF ON EECLRF.EXT_EDITOR_EDIT_FLAG_KEY = EF.EXT_EDITOR_EDIT_FLAG_KEY
LEFT JOIN 
    PAYOR_DW.CLAIM_LN_FCT_TO_REVIEW_TRIGGER CLFRT ON ACLF.CLAIM_LINE_FACT_KEY = CLFRT.CLAIM_LINE_FACT_KEY 
LEFT JOIN 
    PAYOR_DW.REVIEW_REPAIR_TRIGGER RRT ON CLFRT.REVIEW_REPAIR_TRIGGER_KEY = RRT.REVIEW_REPAIR_TRIGGER_KEY  
LEFT JOIN
    payor_dw.DATE_DIMENSION dd ON rc.RECEIPT_DATE_KEY = dd.DATE_KEY
LEFT JOIN
    payor_dw.SUPPLIER ashf ON rc.SUPPLIER_KEY = ashf.SUPPLIER_KEY
LEFT JOIN
    payor_dw.POSTAL_ADDRESS pa ON ashf.SUPPLIER_CORR_ADDRESS_KEY = pa.POSTAL_ADDRESS_KEY
--LEFT JOIN
--    payor_dw.CLAIM_LINE_FACT_TO_DIAG CLFD ON aclf.CLAIM_LINE_FACT_KEY = CLFD.CLAIM_LINE_FACT_KEY
--LEFT JOIN
--    payor_dw.DATE_DIMENSION dt_st ON aclf.SERVICE_START_DATE_KEY = dt_st.DATE_KEY
--LEFT JOIN
--    payor_dw.DATE_DIMENSION dt_end ON aclf.SERVICE_END_DATE_KEY = dt_end.DATE_KEY
WHERE
    rc.row_num = 1
    AND RRT.TRIGGER_DESC = 'Claim flagged for review by external bundling/fraud detection system.'
    --AND rc.CLAIM_HCC_ID = '2024211002703'
    AND EF.flag_mnemonic IN ('gcCCSD','gcCCS')
--    AND dt_st.DATE_VALUE  >= TO_TIMESTAMP('2024-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
--    AND dt_end.DATE_VALUE < TO_TIMESTAMP('2024-10-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
--GROUP BY 
--rc.CLAIM_HCC_ID, aclf.CLAIM_LINE_HCC_ID, rc.CLAIM_STATUS, rc.CLAIM_TYPE_NAME, csc.CLAIM_SOURCE_NAME, rc.SUBMITTED_SUBSCRIBER_ID, dt_st.DATE_VALUE, dt_end.DATE_VALUE, 
--EF.flag_action, EF.flag_message, EF.flag_mnemonic, aclf.SERVICE_CODE, RRT.TRIGGER_DESC, rc.SI_SUPPLIER_NPI, ashf.SUPPLIER_NPI, RC.SI_SUPPLIER_ID, ashf.SUPPLIER_HCC_ID, rc.SI_SUPPLIER_NAME,
--ashf.SUPPLIER_NAME, rc.SI_SUPPLIER_ADDRESS, rc.SI_SUPPLIER_CITY, rc.SI_SUPPLIER_STATE, rc.SI_SUPPLIER_COUNTRY,rc.SI_SUPPLIER_ZIPCODE, 
--PA.ADDRESS_LINE, PA.CITY_NAME, PA.STATE_CODE, PA.COUNTY_CODE, PA.ZIP_CODE, dd.DATE_VALUE, rc.MOST_RECENT_PROCESS_TIME







    
    